### ISSUE TITLE
Modules parts and drivers

### ISSUE THREAD

**Issue by hacko-bede** [OrchardCMS/OrchardCore.Samples#10]
Hey @sebastienros do you plan to update samples to include also how to create a Module with parts and drivers. What are the packages that should be referenced?
I could not find any documentation related to this topic for now.

**Comment by sebastienros** [comment]
Drivers and parts are specific to the theming engine, so obviously for the Orchard Core repos.
But I agree that it makes sense to add documentation on it, can you file the issue on the Orchard core repos?
