### ISSUE TITLE
This project isn't up to date with current release

### ISSUE THREAD

**Issue by Stowflake** [OrchardCMS/OrchardCore.Samples#11]

**Comment by Stowflake** [comment]
If you would like to use the current package you need to switch "services.AddModules()" with "services.AddOrchardCore().AddMvc();" within ConfigureServices in the method Startup.vs and then switch "app.UseModules()" with "app.UseOrchardCore()" in the method Configure within Startup.cs

**Comment by sebastienros** [comment]
Fixed
