### ISSUE TITLE
Getting the list of available modules in the solution

### ISSUE THREAD

**Issue by ampadashi** [OrchardCMS/OrchardCore.Samples#13]
I wonder if it is possible to get the list of all available modules in the solution using some API in the OrchardCore. If it is, please let me know where the right documentation can be found. In order to do so, I have already set up a logic, but i think it will be great if we could use some API in OrchardCore.
Thanks for your awesome framework. It is really great!

**Comment by sebastienros** [comment]
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Abstractions/Extensions/IExtensionManager.cs
