### ISSUE TITLE
AddModules is do not difine

### ISSUE THREAD

**Issue by jaytu** [OrchardCMS/OrchardCore.Samples#15]
hello:
my project behind update package OrchardCore.Application.Mvc.Targets beta1.0 to 3.0
the project is error  
below the code
    public static class ModularApplicationBuilderExtensions
    {
        public static IApplicationBuilder ConfigureModules(this IApplicationBuilder app, Action<ModularApplicationBuilder> modules);
        public static IApplicationBuilder UseModules(this IApplicationBuilder app, Action<ModularApplicationBuilder> modules = null);
        public static ModularApplicationBuilder UseStaticFilesModules(this ModularApplicationBuilder modularApp);
    }

it‘s remove

how to use beta 3.0 to create this OrchardCore.Samples

**Comment by jasper-d** [comment]
Use `AddOrchardCore().AddMvc()` and `UseOrchardCore()` instead.

Use the following Startup in Module1 to fix the route:

    public class Startup : StartupBase
    {
        // This method gets called by the runtime. Use this method to add services to the container.
        // For more information on how to configure your application, visit https://go.microsoft.com/fwlink/?LinkID=398940
        public override void ConfigureServices(IServiceCollection services)
        {
        }

        // This method gets called by the runtime. Use this method to configure the HTTP request pipeline.
        public override void Configure(IApplicationBuilder app, IRouteBuilder routes, IServiceProvider serviceProvider)
        {
            routes.MapAreaRoute(name: "Module1", areaName: "Module1", template: "Module1/{controller=Home}/{action=Index}");
        }
    }

**Comment by daoqiang** [comment]
it is not work

**Comment by sebastienros** [comment]
Fixed
