### ISSUE TITLE
Documentation is missing admin/user login instructions

### ISSUE THREAD

**Issue by weedkiller** [OrchardCMS/OrchardCore.Samples#16]
Hi I am happy to add/help with documentation, I could not find how to login as a admin, usage.

I would also ask for list of hosting/compatible sites, especially since many chew down the RAM, we need to have some verified providers and how much RAM do we need, how much disk I/O do we need etc. Many choke RAM and disk i/o

thanks

**Comment by sebastienros** [comment]
This sample doesn't have an admin module. Look at OrchardCore CMS (https://github.com/OrchardCMS/OrchardCore)
