### ISSUE TITLE
POST request not working

### ISSUE THREAD

**Issue by tforsberg** [OrchardCMS/OrchardCore.Samples#25]
I forked this repo and added a "PersonController.cs" file.  GET and GET by Id are working fine with a small sample data class (Person model)

But I can't get POST requests to work.  I'm guessing this is an error on my part, but I've tried everything I know of.

When I try Post, I get the following error.

{
"type": "https://tools.ietf.org/html/rfc7231#section-6.5.1",
"title": "Bad Request",
"status": 400,
"traceId": "|12ea6c65-4c366455b553a452."
}

I am using Postman app for testing.

https://github.com/tforsberg/OrchardCore.Samples

**Comment by jeremycook** [comment]
Hi @tforsberg I took a look at your fork and at-a-glance it looked fine to me. Nothing jumped out. There is nothing special about MVC controllers in Orchard. They are standard MVC controllers. Routing could cause issues, but if routing was the problem I would assume you would get a 404 and not 400. Sorry I can't be more helpful at this time.

Supposing you haven't already figured it out, I would encourage you to lean on the logging system to get a clearer picture of what is causing the error. That almost always helps me out. See: https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1

And if you would like more help with this the [Orchard Core Gitter channel](https://gitter.im/OrchardCMS/OrchardCore) is a very friendly place.

**Comment by sebastienros** [comment]
Antiforgery token is missing.

We talked about it during last meeting. This issue is opened at least once a week.
We'll talk to the mvc team on how to display an actual error message instead of a cryptic empty 400.

**Comment by atorres16** [comment]
2022 still getting these errors
