### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by dmaziuk** [OrchardCMS/OrchardCore.Samples#27]
You should really get the docs updated: the template app referenced here: https://docs.orchardcore.net/en/ag-docs/docs/guides/create-modular-application-mvc/ won't build in VS2019 and Sebastian's demo linked from that page is so out of date almost nothing he shows matches the current VS, or .NET, or Orchard.

This sample is the only one that works as of Nov 2020.

**Comment by agriffard** [comment]
The correct url is https://docs.orchardcore.net/en/dev/docs/guides/create-modular-application-mvc/

**Comment by sebastienros** [comment]
@dmaziuk where did you find this link so we can fix it?

**Comment by dmaziuk** [comment]
google found it, to my knowledge nobody could ever get them to "fix" their search results.
