### ISSUE TITLE
Turkish Characters in URL Slug

### ISSUE THREAD

**Issue by fabrikamedya** [OrchardCMS/OrchardCore.Samples#48]
Hello,

I am using OrchardCore in Turkish. In Turkish, there are characters such as ı, I, ş, Ş, ö, Ö, ü, Ü, ğ, Ğ, ç, and Ç. I am experiencing an issue where, when I use Turkish characters in titles, the URL slug is also created with Turkish characters. For example: Title: Başlık, Url: “/Baslık”. And finally, the page does not load. How can I fix this issue?

**Comment by jeremycook** [comment]
@fabrikamedya I'd encourage you to raise this issue in the Orchard Core repo (https://github.com/OrchardCMS/OrchardCore/issues). Since there isn't anything specifically about the Samples project that would cause this.

**Comment by agriffard** [comment]
Closing it.
