### ISSUE TITLE
Are modules supported on an existing MVC app

### ISSUE THREAD

**Issue by MrJoe** [OrchardCMS/OrchardCore.Samples#7]
Is it possible to use the `UseModules()` with an existing MVC app? I'd like to keep the existing aspnet core 2.0 mvc app and extend it further with new modules

I was hoping it would be possible to use
app.UseModules(); in the Startup.cs, I am not sure whether to keep the app.UseMvc like this:

```
app.UseModules();
app.UseMvc(routes => {
		routes.MapRoute(
			name: "default",
			template: "{controller=Home}/{action=Index}/{id?}");
	});
```

I tried with and without the app.UseMvc but it both cases doesn't seem to use the existing routes anymore. It only seems to find the Controllers / actions which have a route attribute in the existing mvc project and not the other controllers within the existing mvc project. 

I am using OrchardCore.Application.Mvc.Targets from nuget 1.0.0-beta1-3667.

Is this supposed to be a supported scenario at all?

**Comment by sebastienros** [comment]
I am not yet sure it can work, I will try and see what is happening.
In the meantime you can also convert your existing app into a separate module.
