### ISSUE TITLE
Multitenant sample not working

### ISSUE THREAD

**Issue by psijkof** [OrchardCMS/OrchardCore.Samples#9]
<CanDeleteMe />

**Comment by psijkof** [comment]
I think I am mixing things here. The above error has nothing to do with the Sample and is the result of multiple insider/preview versions of vs and windows on the dev box I tried the example.

The sample works perfectly fine!

**Comment by psijkof** [comment]
Just doesn't work with beta2-* release (yet)?!

**Comment by shahidullahdurrani** [comment]
@sebastienros 
Facing same issue Multi Tenant Sample isn't working returns 404.
I have also tried on my custom solution same case gets repeat - 404
https://github.com/shahidullahdurrani/OrchardCoreTenancy

**Comment by sebastienros** [comment]
Fixed
